# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1


orbs:
  ruby: circleci/ruby@0.2.1 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run:
          name: Install Bundler 2.1.4
          command: gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/save-cache
      - run:
          name: Tests
          command: bin/test
      - store_artifacts:
          path: coverage

# What to do next? Set up a test job. Please see
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
